config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :designs

  get 'numbers', to: 'categories#numbers'
  get 'letters', to: 'categories#letters'
  get 'objects', to: 'categories#objects'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/design.rb
class Design < ApplicationRecord
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def numbers
    @designs = Design.where(category: "Numbers")
  end

  def letters
    @designs = Design.where(category: "Letters")
  end

  def objects
    @designs = Design.where(category: "Objects")
  end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  # before_action :set_design, only: %i[ show ]

  def index
    @designs = Design.all
  end

  def show
    set_design
    @design = Design.find(params[:id])
  end

  def new
    @design = Design.new
  end

  def create
    @design = Design.new(design_params)

    if @design.save!
      redirect_to @design, notice: "Design was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def design_params
      params.require(:design).permit(:title, :category, :photo) #photos: [] if you want to allow multiple photos?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/letters.html.erb
<div class="letters-main-container">
  <%= link_to root_path, class: "back-button" do %>
    <h3> <-- Back </h3>
  <% end %>
  <h1 class="category-title">Letters</h1>
  <%= render 'shared/design_card_display' %>
</div>
<%= render 'shared/footer' %>

app/views/categories/numbers.html.erb
<div class="numbers-main-container">
  <%= link_to root_path, class: "back-button" do %>
    <h3> <-- Back </h3>
  <% end %>
  <h1 class="category-title">Numbers</h1>
  <%= render 'shared/design_card_display' %>
</div>

<%= render 'shared/footer' %>

app/views/categories/objects.html.erb
<div class="objects-main-container">
  <%= link_to root_path, class: "back-button" do %>
    <h3> <-- Back </h3>
  <% end %>
  <h1 class="category-title">Objects / Landscapes </h1>
  <%= render 'shared/design_card_display' %>
</div>

<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QQLATLAS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-content-container">
  <div class="banner">
    <h1 class="banner-title">QQL Atlas</h1>
    <p class="banner-description">
      QQL is a collaborative experiment in generative art by Tyler Hobbs and Dandelion Wist Mané.
    </p>

    <p class="banner-description">
      This gallery is a tribute to these artists and their work, by curating and displaying cool outputs in different visual categories of the QQL Algorithm.
    </p>
  </div>

  <div class="cards-container">
    <div class="col-lg-4">
      <%= link_to letters_path do %>
        <p>Letters</p>
        <%= image_tag('letter_U_optimized.png') %>
      <% end %>
    </div>

    <div class="col-lg-4">
      <%= link_to numbers_path do %>
        <p>Numbers</p>
        <%= image_tag('number_7_optimized.png') %>
      <% end %>
    </div>

    <div class="col-lg-4">
      <%= link_to objects_path do %>
        <p>Landscapes / Objects </p>
        <%= image_tag('object_wave_optimized.png') %>
      <% end %>
    </div>
  </div>

  <div class="more-categories">
    <p>More categories soon...</p>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/shared/_design_card_display.html.erb
<div class="designs-cards-cointainer">
  <div class="designs-flex-container">
    <% @designs.each do |design| %>
      <div class="design-card">
        <h5 class="card-title"><%= design.title%> </h5>
        <div class="design-card-image">
        <% if design.photo.attached? %>
          <%= cl_image_tag design.photo.key, height: 350, width: 280, crop: :fill %>
         <% end %>
       </div>
      </div>
    <% end %>
   </div>
</div>

app/views/shared/_footer.html.erb
  <div class="footer">
  <a href="http://twitter.com/juaneseth">
    <p>By @juaneseth</p>
  </a>
  </div>